version: '3'

services:
  traefik:
    image: traefik
    command: --api.insecure=true --providers.docker=true
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"

  nginx:
    image: nginx
    ports:
      - "8081:80"
    networks:
      - app-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


  

networks:
  app-net:

